baseURL = "/"
languageCode = "es-es"
title = "David Daza"
description = "Fullstack Developer. Code enthusiasm."
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    lineNos = true
    tabWidth = 2