baseURL = "/"
languageCode = "es-es"
title = "David Daza"
description = "Fullstack Developer. Code enthusiasm."
googleAnalytics = "UA-132671209-1"
disqusShortname = "ddazal"

[markup]
  [markup.highlight]
    lineNos = true
    tabWidth = 2